using NUnit.Framework;
using PowerScript.Compiler;
using PowerScript.Interpreter;
using PowerScript.Interpreter.DotNet;
using PowerScript.Parser.Processors.Base;
using PowerScript.Parser.Processors.ControlFlow;
using PowerScript.Parser.Processors.Expressions;
using PowerScript.Parser.Processors.Scoping;
using PowerScript.Parser.Processors.Statements;
using PowerScript.Runtime;
using PowerScript.Common.Logging;

namespace PowerScript.Integration.Tests;

[TestFixture]
[Category("Complex")]
[Description("Complex feature tests covering advanced language constructs and combinations")]
public class ComplexFeatureTests
{
    [SetUp]
    public void Setup()
    {
        // Suppress logging during tests
        LoggerService.UseNullLogger();

        // Initialize the new separated domains architecture
        TokenProcessorRegistry registry = new();
        DotNetLinker dotNetLinker = new();
        ScopeBuilder scopeBuilder = new(registry);

        // Register all the processors (like CLI does)
        RegisterProcessors(registry, scopeBuilder);

        PowerScriptCompilerNew compiler = new(registry, dotNetLinker, scopeBuilder);
        PowerScriptExecutor executor = new();
        _interpreter = new PowerScriptInterpreter(compiler, executor);

        _output = new StringWriter();
        Console.SetOut(_output);
    }

    private void RegisterProcessors(TokenProcessorRegistry registry, ScopeBuilder scopeBuilder)
    {
        // Create parameter processor (helper, not a token processor)
        ParameterProcessor parameterProcessor = new();

        // Register all token processors (matching LanguageTestBase)
        registry.Register(new StaticTypeVariableProcessor());
        registry.Register(new FunctionProcessor(parameterProcessor));
        registry.Register(new NetMemberAccessStatementProcessor());
        registry.Register(new LinkStatementProcessor());
        registry.Register(new FlexVariableProcessor());
        registry.Register(new VariableAssignmentProcessor());
        registry.Register(new CycleLoopProcessor(scopeBuilder));
        registry.Register(new IfStatementProcessor(scopeBuilder));
        registry.Register(new ReturnStatementProcessor());
        // NOTE: PrintStatementProcessor removed - PRINT is now a function in stdlib/IO.ps
        registry.Register(new FunctionCallStatementProcessor());
        registry.Register(new FunctionCallProcessor());
        registry.Register(new ExecuteCommandProcessor());
        registry.Register(new NetMethodCallProcessor());
        registry.Register(new VariableDeclarationProcessor());
    }

    [TearDown]
    public void TearDown()
    {
        _output?.Dispose();
        Console.SetOut(Console.Out);
    }

    private PowerScriptInterpreter _interpreter;
    private StringWriter _output;

    private string GetOutput()
    {
        return _output.ToString();
    }

    [Test]
    [Category("Arrays")]
    [Description("Test 3.1: Bubble sort algorithm with array literals")]
    public void Test_3_1_BubbleSort()
    {
        string path = "../../../../../test-scripts/complex/3_1_bubble_sort.ps";
        Assert.DoesNotThrow(() => _interpreter.ExecuteFile(path));

        string output = GetOutput();
        // Verify sorted output contains numbers in ascending order
        Assert.That(output, Does.Contain("11"), "Should contain smallest number");
        Assert.That(output, Does.Contain("90"), "Should contain largest number");
    }

    [Test]
    [Category("Arrays")]
    [Description("Test 3.2: Multi-dimensional array simulation (matrix operations)")]
    public void Test_3_2_MatrixOperations()
    {
        string path = "../../../../../test-scripts/complex/3_2_matrix_operations.ps";
        Assert.DoesNotThrow(() => _interpreter.ExecuteFile(path));

        string output = GetOutput();
        Assert.That(output, Is.Not.Empty, "Should produce output");
    }

    [Test]
    [Category("Pathfinding")]
    [Description("Test 3.3: Maze solver using 1D array as 2D grid")]
    public void Test_3_3_MazeSolver()
    {
        string path = "../../../../../test-scripts/complex/3_3_maze_solver.ps";
        Assert.DoesNotThrow(() => _interpreter.ExecuteFile(path));

        string output = GetOutput();
        Assert.That(output, Does.Contain("GOAL REACHED"), "Should find a path through the maze");
        Assert.That(output, Does.Contain("8"), "Path length should be 8");
    }

    [Test]
    [Category("Loops")]
    [Description("Test 3.4: Auto-generated loop variables (A, B, C)")]
    public void Test_3_4_AutoGeneratedVariables()
    {
        string path = "../../../../../test-scripts/complex/3_4_auto_generated_variables.ps";
        Assert.DoesNotThrow(() => _interpreter.ExecuteFile(path));

        string output = GetOutput();
        // Should print A values (0, 1) and B values (0, 1, 2) for each A
        Assert.That(output, Does.Contain("0"), "Should contain A=0");
        Assert.That(output, Does.Contain("1"), "Should contain A=1 or B=1");
        Assert.That(output, Does.Contain("2"), "Should contain B=2");
    }

    [Test]
    [Category("Loops")]
    [Description("Test 3.5: Triple-nested auto-generated loop variables (A, B, C)")]
    public void Test_3_5_TripleNestedLoops()
    {
        string path = "../../../../../test-scripts/complex/3_5_triple_nested_loops.ps";
        Assert.DoesNotThrow(() => _interpreter.ExecuteFile(path));

        string output = GetOutput();
        Assert.That(output, Does.Contain("8"), "2*2*2 iterations should give count=8");
    }

    [Test]
    [Category("Loops")]
    [Description("Test 3.6: Mixed explicit and auto-generated loop variables")]
    public void Test_3_6_MixedLoopVariables()
    {
        string path = "../../../../../test-scripts/complex/3_6_mixed_loop_variables.ps";
        Assert.DoesNotThrow(() => _interpreter.ExecuteFile(path));

        string output = GetOutput();
        // outer is explicitly named, inner loop gets 'A'
        Assert.That(output, Does.Contain("0"), "Should contain outer=0");
        Assert.That(output, Does.Contain("1"), "Should contain outer=1");
    }

    [Test]
    [Category("Recursion")]
    [Description("Test 3.7: Factorial using recursion")]
    public void Test_3_7_Factorial()
    {
        string path = "../../../../../test-scripts/complex/3_7_factorial.ps";
        Assert.DoesNotThrow(() => _interpreter.ExecuteFile(path));

        string output = GetOutput();
        Assert.That(output, Does.Contain("120"), "5! should be 120");
    }

    [Test]
    [Category("Recursion")]
    [Description("Test 3.8: Fibonacci sequence using recursion")]
    public void Test_3_8_Fibonacci()
    {
        string path = "../../../../../test-scripts/complex/3_8_fibonacci.ps";
        Assert.DoesNotThrow(() => _interpreter.ExecuteFile(path));

        string output = GetOutput();
        Assert.That(output, Does.Contain("13"), "7th Fibonacci number should be 13");
    }

    [Test]
    [Category("Algorithms")]
    [Description("Test 3.9: Prime number detection")]
    public void Test_3_9_PrimeDetection()
    {
        string path = "../../../../../test-scripts/complex/3_9_prime_detection.ps";
        Assert.DoesNotThrow(() => _interpreter.ExecuteFile(path));

        string output = GetOutput();
        Assert.That(output, Does.Contain("1"), "17 is prime");
        Assert.That(output, Does.Contain("0"), "18 is not prime");
    }

    [Test]
    [Category("Algorithms")]
    [Description("Test 3.10: Greatest Common Divisor (GCD) using Euclidean algorithm")]
    public void Test_3_10_GCD()
    {
        string path = "../../../../../test-scripts/complex/3_10_gcd.ps";
        Assert.DoesNotThrow(() => _interpreter.ExecuteFile(path));

        string output = GetOutput();
        Assert.That(output, Does.Contain("6"), "GCD of 48 and 18 should be 6");
    }

    [Test]
    [Category("ControlFlow")]
    [Description("Test 3.11: Nested IF statements with complex conditions")]
    public void Test_3_11_NestedConditions()
    {
        string path = "../../../../../test-scripts/complex/3_11_nested_conditions.ps";
        Assert.DoesNotThrow(() => _interpreter.ExecuteFile(path));

        string output = GetOutput();
        Assert.That(output, Does.Contain("z is between x and y"), "Should execute nested IF");
    }

    [Test]
    [Category("ControlFlow")]
    [Description("Test 3.12: Complex loop breaking logic")]
    public void Test_3_12_LoopBreaking()
    {
        string path = "../../../../../test-scripts/complex/3_12_loop_breaking.ps";
        Assert.DoesNotThrow(() => _interpreter.ExecuteFile(path));

        string output = GetOutput();
        Assert.That(output, Does.Contain("Found target"), "Should find target");
        Assert.That(output, Does.Contain("Search successful"), "Should confirm success");
    }

    [Test]
    [Category("DataStructures")]
    [Description("Test 3.13: Stack simulation using array")]
    public void Test_3_13_StackSimulation()
    {
        string path = "../../../../../test-scripts/complex/3_13_stack_simulation.ps";
        Assert.DoesNotThrow(() => _interpreter.ExecuteFile(path));

        string output = GetOutput();
        Assert.That(output, Does.Contain("30"), "Should pop value 30");
    }

    [Test]
    [Category("DataStructures")]
    [Description("Test 3.14: Queue simulation using array")]
    public void Test_3_14_QueueSimulation()
    {
        string path = "../../../../../test-scripts/complex/3_14_queue_simulation.ps";
        Assert.DoesNotThrow(() => _interpreter.ExecuteFile(path));

        string output = GetOutput();
        Assert.That(output, Does.Contain("5"), "Should dequeue value 5 (FIFO)");
    }

    [Test]
    [Category("Math")]
    [Description("Test 3.15: Power function (exponentiation)")]
    public void Test_3_15_PowerFunction()
    {
        string path = "../../../../../test-scripts/complex/3_15_power_function.ps";
        Assert.DoesNotThrow(() => _interpreter.ExecuteFile(path));

        string output = GetOutput();
        Assert.That(output, Does.Contain("256"), "2^8 should be 256");
    }

    [Test]
    [Category("Math")]
    [Description("Test 3.16: Square root approximation using Newton's method")]
    public void Test_3_16_SquareRoot()
    {
        string path = "../../../../../test-scripts/complex/3_16_square_root.ps";
        Assert.DoesNotThrow(() => _interpreter.ExecuteFile(path));

        string output = GetOutput();
        Assert.That(output, Does.Contain("4"), "Square root of 16 should be approximately 4");
    }

    [Test]
    [Category("Arrays")]
    [Description("Test 3.17: Array reversal")]
    public void Test_3_17_ArrayReversal()
    {
        string path = "../../../../../test-scripts/complex/3_17_array_reversal.ps";
        Assert.DoesNotThrow(() => _interpreter.ExecuteFile(path));

        string output = GetOutput();
        Assert.That(output, Does.Contain("5"), "First element should be 5");
        Assert.That(output, Does.Contain("1"), "Last element should be 1");
    }

    [Test]
    [Category("Algorithms")]
    [Description("Test 3.18: Linear search in array")]
    public void Test_3_18_LinearSearch()
    {
        string path = "../../../../../test-scripts/complex/3_18_linear_search.ps";
        Assert.DoesNotThrow(() => _interpreter.ExecuteFile(path));

        string output = GetOutput();
        Assert.That(output, Does.Contain("4"), "Target 9 should be found at index 4");
    }

    [Test]
    [Category("Performance")]
    [Description("Test 3.19: Deep nesting stress test")]
    public void Test_3_19_DeepNesting()
    {
        string path = "../../../../../test-scripts/complex/3_19_deep_nesting.ps";
        Assert.DoesNotThrow(() => _interpreter.ExecuteFile(path));

        string output = GetOutput();
        Assert.That(output, Does.Contain("100"), "5*5*4 iterations should give sum=100");
    }

    [Test]
    [Category("Performance")]
    [Description("Test 3.20: Large array operations")]
    public void Test_3_20_LargeArray()
    {
        string path = "../../../../../test-scripts/complex/3_20_large_array.ps";
        Assert.DoesNotThrow(() => _interpreter.ExecuteFile(path));

        string output = GetOutput();
        Assert.That(output, Does.Contain("210"), "Sum of 1 to 20 should be 210");
    }

    [Test]
    [Category("EdgeCases")]
    [Description("Test 3.21: Zero iterations loop")]
    public void Test_3_21_ZeroIterations()
    {
        string path = "../../../../../test-scripts/complex/3_21_zero_iterations.ps";
        Assert.DoesNotThrow(() => _interpreter.ExecuteFile(path));

        string output = GetOutput();
        Assert.That(output, Does.Contain("0"), "Count should remain 0");
    }

    [Test]
    [Category("EdgeCases")]
    [Description("Test 3.22: Division and modulo operations")]
    public void Test_3_22_DivisionModulo()
    {
        string path = "../../../../../test-scripts/complex/3_22_division_modulo.ps";
        Assert.DoesNotThrow(() => _interpreter.ExecuteFile(path));

        string output = GetOutput();
        Assert.That(output, Does.Contain("3"), "17 / 5 should be 3");
        Assert.That(output, Does.Contain("2"), "17 % 5 should be 2");
    }

    [Test]
    [Category("EdgeCases")]
    [Description("Test 3.23: Operator precedence")]
    public void Test_3_23_OperatorPrecedence()
    {
        string path = "../../../../../test-scripts/complex/3_23_operator_precedence.ps";
        Assert.DoesNotThrow(() => _interpreter.ExecuteFile(path));

        string output = GetOutput();
        // Depending on implementation, should respect precedence
        Assert.That(output, Is.Not.Empty, "Should produce a result");
    }

    [Test]
    [Category("Integration")]
    [Description("Test 3.24: Complete program combining multiple features")]
    public void Test_3_24_IntegrationTest()
    {
        string path = "../../../../../test-scripts/complex/3_24_integration_test.ps";
        Assert.DoesNotThrow(() => _interpreter.ExecuteFile(path));

        string output = GetOutput();
        // 2^2 + 4^2 + 6^2 + 8^2 + 10^2 = 4 + 16 + 36 + 64 + 100 = 220
        Assert.That(output, Does.Contain("220"), "Sum of squares of even numbers should be 220");
    }

    [Test]
    [Category("Integration")]
    [Description("Test 3.25: Collatz conjecture sequence")]
    public void Test_3_25_CollatzSequence()
    {
        string path = "../../../../../test-scripts/complex/3_25_collatz_sequence.ps";
        Assert.DoesNotThrow(() => _interpreter.ExecuteFile(path));

        string output = GetOutput();
        Assert.That(output, Does.Contain("6"), "Collatz sequence from 10 takes 6 steps");
    }
}
